[ci][cross] Use docker to build for Linux and Windows

diff --git a/Makefile.win32 b/Makefile.win32
--- a/Makefile.win32
+++ b/Makefile.win32
@@ -1,8 +1,12 @@
 #
 # Partial Makefile to be included by other Makefiles
 #
-# This defines how to make Windows stuff that can be used
-# on Windows and in cross-builds
+# This defines how to make Windows stuff that can be used on Windows
+# and in cross-builds. If cross-compiling you need to have the
+# appropriate cross-compiler, obviously, but more problematic is the
+# iconv package for the cross environment. For Ubuntu 20/21 the
+# package to get is "win-iconv-mingw-w64-dev", have not been able to
+# find the correct one for Brew/Darwin.
 
 zip: PLATFORM=win32.i686
 .PHONY: zip
@@ -24,30 +28,24 @@ zip: bin/alan.exe bin/arun.exe alan.readme.txt CHANGES.txt alan.readme.windows.t
 bin/winalan.exe bin/winarun.exe :
 	$(error You must first enable or explicitly build winalan.exe and winarun.exe)
 
-$(INNODIR)/ISCC.exe :
-	$(error You have to have the Inno Installer compiler available)
+makensis:
+	@if ! command -v makensis > /dev/null 2>&1 ; then \
+		echo "ERROR: Must have 'makensis' installed to make setup, 'sudo apt install nsis' will probably fix it" ; \
+		exit 1 ; \
+	fi
 
-# Create setup installers for SDK and WinArun using Inno Installer Compiler
+# Create setup installers for SDK and WinArun using NullSoft Installer NSIS
+# Script to replace "variables" in the .nsi files with actual values:
+# (':' instead of customary '/' because of path names in expanded variables)
+NSI_SED = -e 's:<WINGLK_ROOT>:$(WINGLK_ROOT):g' -e 's/<BUILD>/$(VERSION)$(BUILDVERSION)/g' -e 's/<PLATFORM>/$(PLATFORM)/g'
+
 setup: PLATFORM=win32.i686
 .PHONY: setup
-setup: bin/winarun.exe bin/winalan.exe $(INNODIR)/ISCC.exe alan.iss winarun.iss COPYING.txt CHANGES.txt alan.readme.txt alan.readme.windows.txt converter/a2a3.readme.txt
-	@if ldd bin/winalan.exe | grep -q cygwin1.dll ; then \
-		echo ERROR packaging - winalan.exe is dependent on cygwin1.dll ; \
-		exit 1 ; \
-	fi
-	@if ldd bin/winarun.exe | grep -q cygwin1.dll ; then \
-		echo ERROR packaging - winarun.exe is dependent on cygwin1.dll ; \
-		exit 1 ; \
-	fi
-	-rm winarun*setup.exe
-	sed -e s/VERSION/$(VERSION)$(BUILDVERSION)/ -e s/PLATFORM/$(PLATFORM)/ winarun.iss > winarun_tmp.iss
-	$(INNODIR)/ISCC.exe winarun_tmp.iss
-	-rm winarun_tmp.iss
-	-rm alan*setup.exe
-	sed -e s/VERSION/$(VERSION)$(BUILDVERSION)/ -e s/PLATFORM/$(PLATFORM)/ alan.iss > alan_tmp.iss
-	$(INNODIR)/ISCC.exe alan_tmp.iss
-	-rm alan_tmp.iss
-	-rm COPYING.txt CHANGES.txt alan.readme.txt alan.readme.windows.txt converter/a2a3.readme.txt
+setup: buildnumbers makensis winarun.nsi alan.nsi bin/winalan.exe bin/winarun.exe COPYING.txt CHANGES.txt alan.readme.txt alan.readme.windows.txt
+	sed $(NSI_SED) winarun.nsi > winarun.tmp
+	makensis winarun.tmp
+	sed $(NSI_SED) alan.nsi > alan.tmp
+	makensis alan.tmp
 
 COPYING.txt: COPYING
 	unix2dos >$@ <$<
